Table users {
  id integer [primary key]
  username varchar
  password varchar
  created_at timestamp
}

Table feedback {
  id integer [primary key]
  created_at timestamp
  ip varchar
  username varchar
  text varchar
  code varchar
  active boolean
}

Table requests {
  id integer [primary key]
  type varchar
  username varchar
  phone_number varchar
  created_at timestamp
  description varchar
}