export const countries = [
  { name: "Аргентина", code: "AR" },
  { name: "Австрия", code: "AT" },
  { name: "Австралия", code: "AU", top: true },
  { name: "Бельгия", code: "BE"},
  { name: "Бразилия", code: "BR" },
  { name: "Канада", code: "CA", top: true},
  { name: "Швейцария", code: "CH", top: true },
  { name: "Чили", code: "CL" },
  { name: "Китай", code: "CN", top: true },
  { name: "Колумбия", code: "CO" },
  { name: "Чехия", code: "CZ" },
  { name: "Германия", code: "DE", top: true },
  { name: "Дания", code: "DK" },
  { name: "Испания", code: "ES", top: true },
  { name: "Финляндия", code: "FI" },
  { name: "Франция", code: "FR", top: true },
  { name: "Великобритания", code: "GB", top: true },
  { name: "Греция", code: "GR" },
  { name: "Гонконг", code: "HK" },
  { name: "Венгрия", code: "HU"},
  { name: "Индонезия", code: "ID" },
  { name: "Ирландия", code: "IE" },
  { name: "Индия", code: "IN"},
  { name: "Исландия", code: "IS" },
  { name: "Италия", code: "IT", top: true},
  { name: "Южная Корея", code: "KR" },
  { name: "Мексика", code: "MX", top: true },
  { name: "Нидерланды", code: "NL" },
  { name: "Норвегия", code: "NO", top: true },
  { name: "Новая Зеландия", code: "NZ", top: true },
  { name: "Польша", code: "PL", top: true },
  { name: "Португалия", code: "PT" },
  { name: "Румыния", code: "RO" },
  { name: "Россия", code: "RU", top: true },
  { name: "Швеция", code: "SE" },
  { name: "Сингапур", code: "SG" },
  { name: "Словакия", code: "SK" },
  { name: "Турция", code: "TR", top: true },
  { name: "Южная Африка", code: "ZA", top: true },
  { name: "США", code: "US", top: true },
  { name: "Европейский союз", code: "EU", top: true},
  { name: "Япония", code: "JP", top: true},
];
